name: moonpig-api CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # or other versions if you prefer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: yarn test

      - name: Run e2e tests
        run: yarn run test:e2e
