name: moonpig-api CI

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - uses: ./.github/actions/action.yml
        with:
          node-version: '16.x'
      - name: Run unit tests
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
          uses: actions/checkout@v2

      - uses: ./.github/actions/action.yml
        with:
          node-version: '16.x'
      - name: Run e2e tests
        run: yarn run test:e2e
